package com.isw2.util;

public enum ExperimentType {
    FEATURE_SELECTION,
    FEATURE_SELECTION_WITH_UNDER_SAMPLING,
    FEATURE_SELECTION_WITH_OVER_SAMPLING,
    FEATURE_SELECTION_WITH_COST_SENSITIVE_CLASSIFIER_CFN_4,
    FEATURE_SELECTION_WITH_COST_SENSITIVE_CLASSIFIER_CFN_3,
    FEATURE_SELECTION_WITH_COST_SENSITIVE_LEARNING,
    VANILLA
}
