package com.isw2.util;

public enum ExperimentType {
    FEATURE_SELECTION,
    FEATURE_SELECTION_WITH_UNDER_SAMPLING,
    FEATURE_SELECTION_WITH_OVER_SAMPLING,
    FEATURE_SELECTION_WITH_COST_SENSITIVE_CLASSIFIER,
    FEATURE_SELECTION_WITH_COST_SENSITIVE_LEARNING,
    COST_SENSITIVE_CLASSIFIER,
    COST_SENSITIVE_LEARNING,
    OVER_SAMPLING,
    UNDER_SAMPLING,
    VANILLA
}
